/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package isad.w6.practicum.graphical;

/**
 *
 * @author jappie
 */
public class GUI extends javax.swing.JFrame {

	/**
	 * Creates new form GUI
	 */
	public GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _mirrorButton = new javax.swing.JButton();
        _treePainter = new isad.w6.practicum.graphical.TreePainter();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _mirrorButton.setText("Spiegelen");
        _mirrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                _mirrorButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout _treePainterLayout = new javax.swing.GroupLayout(_treePainter);
        _treePainter.setLayout(_treePainterLayout);
        _treePainterLayout.setHorizontalGroup(
            _treePainterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );
        _treePainterLayout.setVerticalGroup(
            _treePainterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 821, Short.MAX_VALUE)
                        .addComponent(_mirrorButton))
                    .addComponent(_treePainter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_mirrorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_treePainter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _mirrorButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event__mirrorButtonMouseClicked
        getTreePainter().setMirrord(!getTreePainter().isMirrord());
		getTreePainter().repaint();
    }//GEN-LAST:event__mirrorButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _mirrorButton;
    private isad.w6.practicum.graphical.TreePainter _treePainter;
    // End of variables declaration//GEN-END:variables

	/**
	 * @return the _treePainter
	 */
	private isad.w6.practicum.graphical.TreePainter getTreePainter() {
		return _treePainter;
	}

	/**
	 * @param treePainter the _treePainter to set
	 */
	private void setTreePainter(isad.w6.practicum.graphical.TreePainter treePainter) {
		this._treePainter = treePainter;
	}
}
