/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package isad.w6.practicum.graph;

import isad.w6.practicum.o1.Node;
import isad.w6.practicum.o1.Tree;

/**
 *
 * @author jappie
 */
public class TreePainter extends javax.swing.JPanel {

	private Tree _tree;
	/**
	 * Creates new form TreePainter
	 */
	public TreePainter() {
		initComponents();
		// tabbed to make a rough assesment of the tree, for debuging reasons
		Node<String> root = new Node<String>("F", null, 
								new Node<String>("D", 
							new Node<String>("I"), new Node<String>("C", 
							new Node<String>("G", null, new Node<String>("A")),
				
																	new Node<String>("B", 
														new Node<String>("A")))));
		_tree = new Tree<String>(root);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
